app:
  name: "mcp-cli"
  version: "1.0.0"
  environment: "development"
  timeout: 30s
  max_retries: 3

servers:
  aws-s3:
    host: "localhost"
    port: 8080
    protocol: "http"
    timeout: 30s
    auth:
      type: "token"
      token: "your-aws-token"
    tls:
      enabled: false
    health_check:
      enabled: true
      interval: 30s
      timeout: 5s
      max_failures: 3
      endpoint: "/health"

  kubernetes:
    host: "localhost"
    port: 8081
    protocol: "http"
    timeout: 30s
    auth:
      type: "basic"
      username: "admin"
      password: "password"
    tls:
      enabled: true
      cert_file: "certs/k8s.crt"
      key_file: "certs/k8s.key"
      skip_verify: false
    health_check:
      enabled: true
      interval: 30s
      timeout: 5s
      max_failures: 3
      endpoint: "/health"

  database:
    host: "localhost"
    port: 8082
    protocol: "http"
    timeout: 30s
    auth:
      type: "none"
    tls:
      enabled: false
    health_check:
      enabled: true
      interval: 30s
      timeout: 5s
      max_failures: 3
      endpoint: "/health"

security:
  jwt:
    secret: "your-super-secret-jwt-key-change-this-in-production"
    expiration: 24h
    issuer: "mcp-cli"
  rate_limit:
    enabled: true
    requests: 100
    window: 1m
  cors:
    enabled: true
    allowed_origins:
      - "*"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowed_headers:
      - "*"

logging:
  level: "info"
  format: "text"
  output: "stdout"
  file: "logs/mcp-cli.log"
  max_size: 100
  max_backups: 3
  max_age: 28

monitoring:
  enabled: true
  host: "localhost"
  port: 9090
  path: "/metrics" 