app:
    name: mcp-cli
    version: 1.0.0
    environment: development
    timeout: 30s
    max_retries: 3
servers: {}
security:
    jwt:
        secret: your-secret-key
        expiration: 24h0m0s
        issuer: mcp-cli
    rate_limit:
        enabled: true
        requests: 100
        window: 1m0s
    cors:
        enabled: true
        allowed_origins:
            - '*'
        allowed_methods:
            - GET
            - POST
            - PUT
            - DELETE
        allowed_headers:
            - '*'
logging:
    level: info
    format: text
    output: stdout
    file: ""
    max_size: 100
    max_backups: 3
    max_age: 28
monitoring:
    enabled: true
    host: localhost
    port: 9090
    path: /metrics
